url: https://christophera.github.io/jekyll-remote_theme-test/
baseurl: /jekyll-remote_theme-test/

remote_theme: "qwtel/hydejack"

plugins:
  - jekyll-remote-theme
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

# The title of your blog. Used in the sidebar and the browser tab.
title:                 Smart Custody

# A short description (~150 chars) of the page used for the meta description tag.
# Can use markdown, but no more than one paragraph (enforced by `>`)
description:           “Smart Custody” is the use of advanced cryptographic tools to improve the *care*, *maintenance*, *control*, and *protection* of digital assets. A project of Blockchain Commons.

# A shorter description for the sidebar.
tagline:               “Smart Custody” is the use of advanced cryptographic tools to improve the *care*, *maintenance*, *control*, and *protection* of digital assets. A project of [Blockchain Commons](https://www.BlockchainCommons.com)

# A list of keywords for your blog
keywords:              [smart, custody, digital, assets, smartcontract, smartcontracts, care, maintenance, protection, control, protection, bitcoin, ethereum]

# This should be the same author as first entry in `_data/authors.yml`.
author:                 Blockchain Commons
#  name:                <firstname> <lastname>
email:                  <info@BlockchainCommons.com>

# Used by `jekyll-seo-tag`:
twitter:             SmartCustody

# This text will appear in a `<small>` tag in the footer of every page.
copyright:           © 2019. All rights reserved.

# A (square) logo for your site.
# If provided, it will be shown at the top of the sidebar.
# It also used by the `jekyll-seo-tag` plugin.
logo:                  transparent-lock-icon.svg

# Sidebar image and theme color of the site.
accent_image:          sidebar-bg.jpg
accent_color:          rgb(79,177,186)

# This is used for the `theme-color` meta tag,
# which changes the background color of the browser UI in certain browsers.
# Defaults to `accent_color`.
theme_color:           rgb(25,55,71)

# The string encoding which fonts to fetch from Google Fonts.
# See: <https://hydejack.com/docs/configuration/>
google_fonts:          Roboto+Slab:400|Noto+Sans:400,400i,700,700i

# The text font. Expects a string that is a valid CSS font-family value.
# To change font-weight, see _sass/variables.scss
font:                  Noto Sans, Helvetica, Arial, sans-serif

# The font used for headings. Expects a string that is a valid CSS font-family value.
# To change font-weight, see _sass/variables.scss
font_heading:          Roboto Slab, Helvetica, Arial, sans-serif
